<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2Rz21u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2Rz21u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL2Rz21u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL2Rz21u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL2Rz21u\App_KernelDevDebugContainer([
    'container.build_hash' => 'L2Rz21u',
    'container.build_id' => 'c9482270',
    'container.build_time' => 1750668134,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2Rz21u');
