<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_modules' => [[], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::index'], [], [['text', '/api/modules']], [], [], []],
    'api_module_create' => [[], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::create'], [], [['text', '/api/modules']], [], [], []],
    'api_module_show' => [['id'], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/modules']], [], [], []],
    'api-module_delete' => [['id'], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/modules']], [], [], []],
    'app_module_list' => [[], ['_controller' => 'App\\Controller\\ModuleController::index'], [], [['text', '/']], [], [], []],
    'app_module_show' => [['id'], ['_controller' => 'App\\Controller\\ModuleController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true]], [], [], []],
    'app_module_create' => [[], ['_controller' => 'App\\Controller\\ModuleController::create'], [], [['text', '/create']], [], [], []],
    'App\Controller\Api\ModuleApiController::index' => [[], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::index'], [], [['text', '/api/modules']], [], [], []],
    'App\Controller\Api\ModuleApiController::create' => [[], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::create'], [], [['text', '/api/modules']], [], [], []],
    'App\Controller\Api\ModuleApiController::show' => [['id'], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/modules']], [], [], []],
    'App\Controller\Api\ModuleApiController::delete' => [['id'], ['_controller' => 'App\\Controller\\Api\\ModuleApiController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/modules']], [], [], []],
    'App\Controller\ModuleController::index' => [[], ['_controller' => 'App\\Controller\\ModuleController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\ModuleController::show' => [['id'], ['_controller' => 'App\\Controller\\ModuleController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true]], [], [], []],
    'App\Controller\ModuleController::create' => [[], ['_controller' => 'App\\Controller\\ModuleController::create'], [], [['text', '/create']], [], [], []],
];
