<?php

namespace ContainerL2Rz21u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Cvb8hsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Cvb8hs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Cvb8hs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'measurementRepository' => ['privates', 'App\\Repository\\MeasurementRepository', 'getMeasurementRepositoryService', true],
            'module' => ['privates', '.errored..service_locator..Cvb8hs.App\\Entity\\Module', NULL, 'Cannot autowire service ".service_locator..Cvb8hs": it needs an instance of "App\\Entity\\Module" but this type has been excluded in "config/services.yaml".'],
            'sensorRepository' => ['privates', 'App\\Repository\\SensorRepository', 'getSensorRepositoryService', true],
        ], [
            'measurementRepository' => 'App\\Repository\\MeasurementRepository',
            'module' => 'App\\Entity\\Module',
            'sensorRepository' => 'App\\Repository\\SensorRepository',
        ]);
    }
}
