<?php

namespace ContainerL2Rz21u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RNYN0s3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RNYN0s3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RNYN0s3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Api\\ModuleApiController::create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Api\\ModuleApiController::delete' => ['privates', '.service_locator.n6IIUav', 'get_ServiceLocator_N6IIUavService', true],
            'App\\Controller\\Api\\ModuleApiController::index' => ['privates', '.service_locator.BsfINrE', 'get_ServiceLocator_BsfINrEService', true],
            'App\\Controller\\Api\\ModuleApiController::show' => ['privates', '.service_locator..Cvb8hs', 'get_ServiceLocator__Cvb8hsService', true],
            'App\\Controller\\ModuleController::create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModuleController::show' => ['privates', '.service_locator..Cvb8hs', 'get_ServiceLocator__Cvb8hsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Api\\ModuleApiController:create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Api\\ModuleApiController:delete' => ['privates', '.service_locator.n6IIUav', 'get_ServiceLocator_N6IIUavService', true],
            'App\\Controller\\Api\\ModuleApiController:index' => ['privates', '.service_locator.BsfINrE', 'get_ServiceLocator_BsfINrEService', true],
            'App\\Controller\\Api\\ModuleApiController:show' => ['privates', '.service_locator..Cvb8hs', 'get_ServiceLocator__Cvb8hsService', true],
            'App\\Controller\\ModuleController:create' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ModuleController:show' => ['privates', '.service_locator..Cvb8hs', 'get_ServiceLocator__Cvb8hsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Api\\ModuleApiController::create' => '?',
            'App\\Controller\\Api\\ModuleApiController::delete' => '?',
            'App\\Controller\\Api\\ModuleApiController::index' => '?',
            'App\\Controller\\Api\\ModuleApiController::show' => '?',
            'App\\Controller\\ModuleController::create' => '?',
            'App\\Controller\\ModuleController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Api\\ModuleApiController:create' => '?',
            'App\\Controller\\Api\\ModuleApiController:delete' => '?',
            'App\\Controller\\Api\\ModuleApiController:index' => '?',
            'App\\Controller\\Api\\ModuleApiController:show' => '?',
            'App\\Controller\\ModuleController:create' => '?',
            'App\\Controller\\ModuleController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
