<?php

namespace ContainerL2Rz21u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..Cvb8hs.App\Entity\Module' shared service.
     *
     * @return \App\Entity\Module
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..Cvb8hs": it needs an instance of "App\\Entity\\Module" but this type has been excluded in "config/services.yaml".');
    }
}
