<?php

namespace ContainerPSlVFGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateModuleStatusCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GenerateModuleStatusCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GenerateModuleStatusCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-module-status', [], 'Generate random status for modules and update them in the database', false, #[\Closure(name: 'App\\Command\\GenerateModuleStatusCommand')] fn (): \App\Command\GenerateModuleStatusCommand => ($container->privates['App\\Command\\GenerateModuleStatusCommand'] ?? $container->load('getGenerateModuleStatusCommandService')));
    }
}
