<?php

namespace ContainerPSlVFGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateMeasurementCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateMeasurementCommand' shared autowired service.
     *
     * @return \App\Command\GenerateMeasurementCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateMeasurementCommand.php';

        $container->privates['App\\Command\\GenerateMeasurementCommand'] = $instance = new \App\Command\GenerateMeasurementCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:generate-measurement');
        $instance->setDescription('Generate random measurements for sensors and update them in the database');

        return $instance;
    }
}
