<?php

namespace ContainerPSlVFGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateMeasurementCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GenerateMeasurementCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GenerateMeasurementCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-measurement', [], 'Generate random measurements for sensors and update them in the database', false, #[\Closure(name: 'App\\Command\\GenerateMeasurementCommand')] fn (): \App\Command\GenerateMeasurementCommand => ($container->privates['App\\Command\\GenerateMeasurementCommand'] ?? $container->load('getGenerateMeasurementCommandService')));
    }
}
