<?php

namespace ContainerPSlVFGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateModuleStatusCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateModuleStatusCommand' shared autowired service.
     *
     * @return \App\Command\GenerateModuleStatusCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateModuleStatusCommand.php';

        $container->privates['App\\Command\\GenerateModuleStatusCommand'] = $instance = new \App\Command\GenerateModuleStatusCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:generate-module-status');
        $instance->setDescription('Generate random status for modules and update them in the database');

        return $instance;
    }
}
